export default {
  lightTextColor: '#7D848D',
  mediumTextColor: '#1B1E28',
  lightPrimaryColor: '#6759FF',
  white: '#fff',
  black: 'black',
  lightOrange: '#FF7029',
  lightBlueText: '#0D6EFD',
  placeholderColor: '#F7F7F9',
  red: 'red',
  placeholderBackgroundColor: '#E1E5F4',
  placeholderIconColor: '#030047',
  buttonAuthCommon: '#FFCC3E',
  buttonAuthCommonText: '#030047',
  transparent: 'transparent',
  lightGrey: "#cccccc",
  xLightGrey: "#e6e6e6",
  xxLightGrey: "#f2f2f2",
  appColor: '#634871',
  logoBackGroundColor: '#C4C8C3',
  logoBackGroundColor2: '#d8c5c6'
};
