import { IMAGES } from ".";

export const locationData = [
  {
    id: 1,
    name: 'Hunters Gleen',
    location: 'Hunters Glen Court',
    locationImage: IMAGES.Trek1,
    ratings: 4.5,
    roomsAvailable: 2,
    price: 150,
    locationDetails:
      'Enjoy the beauty of summer with various attractions available here, as well as various complete facilities, avaoilable at affordable prices, for all tourists from all accross the world',
    videoUrl:
      'https://my.matterport.com/show/?m=2DB21iorcrM&play=1',
    propertyDetailsPoints: [
      'Panoramic Views',
      'Outdoor Activities',
      'Family-friendly',
      'Spacious Rooms',
      'Modern Amenities',
    ],
    phoneNumber: '1234567900',
    email: 'niladri.reserviour@example.com',
    address: '123 Niladri Rd, Surat, Gujarat 395001',
  },
  {
    id: 2,
    name: 'Sunset Grove',
    location: 'Sunset Grove in Woodlands Valley',
    locationImage: IMAGES.Trek2,
    ratings: 4.7,
    roomsAvailable: 5,
    price: 120,
    locationDetails:
      'Experience the tranquility of nature at this serene reservoir, offering stunning views and peaceful surroundings for a rejuvenating getaway.',
    videoUrl: 'https://my.matterport.com/show/?m=2DB21iorcrM&play=1',
    propertyDetailsPoints: [
      'Vegeterian Family',
      'Vegan',
      'Sunny View',
      '2 BedRoom',
      'Lavisk Collection',
    ],
    phoneNumber: '9876543210',
    email: 'darma.reserviour@example.com',
    address: '456 Darma Blvd, Darma, Gujarat 395002',
  },
  {
    id: 3,
    name: 'Maple Manor',
    location: 'Maple Manor of Forestview Estates',
    locationImage: IMAGES.Trek3,
    ratings: 4.9,
    roomsAvailable: 7,
    price: 100,
    locationDetails:
      'Discover the hidden gem of Surat, where crystal-clear waters and lush greenery create a picturesque setting for a memorable vacation.',
    videoUrl: 'https://my.matterport.com/show/?m=oDf4kqDXCDF&play=1',
    propertyDetailsPoints: [
      'Waterfront Location',
      'Eco-friendly Practices',
      'Spa and Wellness Center',
      'Gourmet Dining',
      'Luxury Accommodations',
    ],
    phoneNumber: '5555555555',
    email: 'niladri2.reserviour@example.com',
    address: '789 Niladri Ln, Surat, Gujarat 395003',
  },
  {
    id: 4,
    name: 'Oakwood Estates',
    location: 'Oakwood Estates in Timberline Township',
    locationImage: IMAGES.Trek4,
    ratings: 4.1,
    roomsAvailable: 3,
    price: 200,
    locationDetails:
      'Immerse yourself in the rich cultural heritage and natural beauty of Darma, where this reservoir offers a unique blend of adventure and relaxation.Immerse yourself in the rich cultural heritage and natural beauty of Darma, where this reservoir offers a unique blend of adventure and relaxation',
    videoUrl:
      'https://my.matterport.com/show/?m=2DB21iorcrM&play=1',
    propertyDetailsPoints: [
      'Panoramic Views',
      'Outdoor Activities',
      'Family-friendly',
      'Spacious Rooms',
      'Modern Amenities',
    ],
    phoneNumber: '1112223333',
    email: 'darma2.reserviour@example.com',
    address: '456 Darma Ave, Darma, Gujarat 395004',
  },
  {
    id: 5,
    name: 'Meadowlark Meadows',
    location: 'Willow Crest at Rivermist Pines',
    locationImage: IMAGES.Trek5,
    ratings: 4.1,
    roomsAvailable: 3,
    price: 200,
    locationDetails:
      'Immerse yourself in the rich cultural heritage and natural beauty of Darma, where this reservoir offers a unique blend of adventure and relaxation.Immerse yourself in the rich cultural heritage and natural beauty of Darma, where this reservoir offers a unique blend of adventure and relaxation',
    videoUrl:
      'https://my.matterport.com/show/?m=2DB21iorcrM&play=1',
    propertyDetailsPoints: [
      'Panoramic Views',
      'Outdoor Activities',
      'Family-friendly',
      'Spacious Rooms',
      'Modern Amenities',
    ],
    phoneNumber: '1112223333',
    email: 'darma2.reserviour@example.com',
    address: '456 Darma Ave, Darma, Gujarat 395004',
  },
  {
    id: 6,
    name: 'Pinecone Pines',
    location: 'Pinecone Pines in Mountainside Village',
    locationImage: IMAGES.Trek6,
    ratings: 4.1,
    roomsAvailable: 3,
    price: 200,
    locationDetails:
      'Immerse yourself in the rich cultural heritage and natural beauty of Darma, where this reservoir offers a unique blend of adventure and relaxation.Immerse yourself in the rich cultural heritage and natural beauty of Darma, where this reservoir offers a unique blend of adventure and relaxation',
    videoUrl:
      'https://my.matterport.com/show/?m=2DB21iorcrM&play=1',
    propertyDetailsPoints: [
      'Panoramic Views',
      'Outdoor Activities',
      'Family-friendly',
      'Spacious Rooms',
      'Modern Amenities',
    ],
    phoneNumber: '1112223333',
    email: 'darma2.reserviour@example.com',
    address: '456 Darma Ave, Darma, Gujarat 395004',
  },
  {
    id: 7,
    name: 'Silverlake Springs',
    location: 'Silverlake Springs in Lakecrest Shores',
    locationImage: IMAGES.Trek7,
    ratings: 4.1,
    roomsAvailable: 3,
    price: 200,
    locationDetails:
      'Immerse yourself in the rich cultural heritage and natural beauty of Darma, where this reservoir offers a unique blend of adventure and relaxation.Immerse yourself in the rich cultural heritage and natural beauty of Darma, where this reservoir offers a unique blend of adventure and relaxation',
    videoUrl:
      'https://my.matterport.com/show/?m=2DB21iorcrM&play=1',
    propertyDetailsPoints: [
      'Panoramic Views',
      'Outdoor Activities',
      'Family-friendly',
      'Spacious Rooms',
      'Modern Amenities',
    ],
    phoneNumber: '1112223333',
    email: 'darma2.reserviour@example.com',
    address: '456 Darma Ave, Darma, Gujarat 395004',
  },
];