export default {
  WelcomeBottomImage: require('../../src/assets/Images/WelcomeBottomImage.png'),
  Life: require('../../src/assets/Images/App/Life.webp'),
  Trek1: require('../../src/assets/Images/App/Trek1.jpeg'),
  Trek2: require('../../src/assets/Images/App/Trek2.jpeg'),
  Trek3: require('../../src/assets/Images/App/Trek3.jpeg'),
  Trek4: require('../../src/assets/Images/App/Trek4.jpeg'),
  Location: require('../../src/assets/Images/App/Location.png'),
  Facebook: require('../../src/assets/Images/App/Facebook.png'),
  Instagram: require('../../src/assets/Images/App/Instagram.png'),
  Twitter: require('../../src/assets/Images/App/Twitter.png'),
  leftArrow: require('../../src/assets/Images/App/leftArrow.svg'),
  NoSearch: require('../../src/assets/Images/App/NoSearch.png'),
  ProfilePicture: require('../../src/assets/Images/App/ProfilePicture.png'),
  // Bottom Tab
  CalendarIcon: require('../../src/assets/Images/BottomTab/CalendarIcon.png'),
  ChatIcon: require('../../src/assets/Images/BottomTab/Chat.png'),
  HomeIcon: require('../../src/assets/Images/BottomTab/HomeIcon.png'),
  ProfileIcon: require('../../src/assets/Images/BottomTab/ProfileIcon.png'),
  SearchIcon: require('../../src/assets/Images/BottomTab/SearchIcon.png'),

  // Auth
  LogIn: require('../../src/assets/Images/Auth/Login.png'),
  Registration: require('../../src/assets/Images/Auth/Registration.png'),
  lock: require('../../src/assets/Images/Auth/Lock.png'),
  Message: require('../../src/assets/Images/Auth/Message.png'),
  BackImage: require('../../src/assets/Images/Auth/BackImage.png'),
  AuthRectangle: require('../../src/assets/Images/Auth/AuthRectangle.png'),
  authImage: require('../../src/assets/Images/Auth/authImage.png'),
  ForgotPassword: require('../../src/assets/Images/Auth/ForgotPassword.png'),
  AtTheRate: require('../../src/assets/Images/Auth/AtTheRate.png'),

  // Profile
  logout: require('../../src/assets/Images/Profile/logout.png'),
  HelpandSupport: require('../../src/assets/Images/Profile/HelpandSupport.png'),
  language: require('../../src/assets/Images/Profile/language.png'),
  rightArrow: require('../../src/assets/Images/Profile/rightArrow.png'),
  shield: require('../../src/assets/Images/Profile/shield.png'),
  edit: require('../../src/assets/Images/Profile/edit.png'),
  close: require('../../src/assets/Images/Profile/close.png'),
};
