export default {
  WelcomeBottomImage: require('../../src/assets/Images/WelcomeBottomImage.png'),
  Life: require('../../src/assets/Images/App/Life.webp'),
  Trek1: require('../../src/assets/Images/App/Trek1.jpg'),
  Trek2: require('../../src/assets/Images/App/Trek2.jpg'),
  Trek3: require('../../src/assets/Images/App/Trek3.jpg'),
  Trek4: require('../../src/assets/Images/App/Trek4.jpg'),
  Trek5: require('../../src/assets/Images/App/Trek5.jpg'),
  Trek6: require('../../src/assets/Images/App/Trek6.jpg'),
  Trek7: require('../../src/assets/Images/App/Trek7.jpg'),
  Trek8: require('../../src/assets/Images/App/Trek8.jpg'),
  Location: require('../../src/assets/Images/App/Location.png'),
  Facebook: require('../../src/assets/Images/App/Facebook.png'),
  Instagram: require('../../src/assets/Images/App/Instagram.png'),
  Twitter: require('../../src/assets/Images/App/Twitter.png'),
  NoSearch: require('../../src/assets/Images/App/NoSearch.png'),
  ProfilePicture: require('../../src/assets/Images/App/ProfilePicture.png'),
  star: require('../../src/assets/Images/App/star.png'),
  dollar: require('../../src/assets/Images/App/dollar.png'),
  bed: require('../../src/assets/Images/App/bed.png'),
  phone: require('../../src/assets/Images/App/phone.png'),
  email: require('../../src/assets/Images/App/email.png'),
  chatBot: require('../../src/assets/Images/App/chatBot.png'),
  plus: require('../../src/assets/Images/App/plus.png'),
  paperPin: require('../../src/assets/Images/App/paperPin.png'),
  send: require('../../src/assets/Images/App/send.png'),
  VirtualTour: require('../../src/assets/Images/App/VirtualTour.png'),
  userPlaceholder: require('../../src/assets/Images/App/userPlaceholder.png'),
  chatPlain: require('../../src/assets/Images/App/chatPlain.png'),
  leftArrow: require('../../src/assets/Images/App/leftArrow.png'),
  menu: require('../../src/assets/Images/App/menu.png'),
  heart: require('../../src/assets/Images/App/heart.png'),
  search: require('../../src/assets/Images/App/search.png'),
  LorenzoIcon: require('../../src/assets/Images/App/LorenzoIcon.png'),
  bathroom: require('../../src/assets/Images/App/bathroom.png'),
  rooms: require('../../src/assets/Images/App/rooms.png'),
  zipCode: require('../../src/assets/Images/App/zipCode.png'),
  imageGallery: require('../../src/assets/Images/App/imageGallery.png'),
  blueprint: require('../../src/assets/Images/App/blueprint.png'),
  call: require('../../src/assets/Images/App/call.png'),
  facility: require('../../src/assets/Images/App/facility.png'),
  pound: require('../../src/assets/Images/App/pound.png'),
  Help: require('../../src/assets/Images/App/Help.png'),

  // Bottom Tab
  CalendarIcon: require('../../src/assets/Images/BottomTab/CalendarIcon.png'),
  ChatIcon: require('../../src/assets/Images/BottomTab/Chat.png'),
  HomeIcon: require('../../src/assets/Images/BottomTab/HomeIcon.png'),
  ProfileIcon: require('../../src/assets/Images/BottomTab/ProfileIcon.png'),
  SearchIcon: require('../../src/assets/Images/BottomTab/SearchIcon.png'),

  // Auth
  LogIn: require('../../src/assets/Images/Auth/Login.png'),
  Registration: require('../../src/assets/Images/Auth/Registration.png'),
  lock: require('../../src/assets/Images/Auth/Lock.png'),
  Message: require('../../src/assets/Images/Auth/Message.png'),
  BackImage: require('../../src/assets/Images/Auth/BackImage.png'),
  AuthRectangle: require('../../src/assets/Images/Auth/AuthRectangle.png'),
  authImage: require('../../src/assets/Images/Auth/authImage.png'),
  ForgotPassword: require('../../src/assets/Images/Auth/ForgotPassword.png'),
  AtTheRate: require('../../src/assets/Images/Auth/AtTheRate.png'),
  logoutPopup: require('../../src/assets/Images/Auth/logoutPopup.png'),
  visible: require('../../src/assets/Images/Auth/visible.png'),
  hide: require('../../src/assets/Images/Auth/hide.png'),
  resetPassword: require('../../src/assets/Images/Auth/resetPassword.png'),
  
  // Profile
  logout: require('../../src/assets/Images/Profile/logout.png'),
  HelpandSupport: require('../../src/assets/Images/Profile/HelpandSupport.png'),
  language: require('../../src/assets/Images/Profile/language.png'),
  rightArrow: require('../../src/assets/Images/Profile/rightArrow.png'),
  shield: require('../../src/assets/Images/Profile/shield.png'),
  edit: require('../../src/assets/Images/Profile/edit.png'),
  close: require('../../src/assets/Images/Profile/close.png'),

  // Video
  Video1: require('../assets/Video/Video.mp4'),
};
