export const ActionTypes = {
  LOGIN_USER: 'LOGIN_USER',
  REGISTERED_USER: 'REGISTERED_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_NUMBER: 'CHANGE_NUMBER',
}